<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'WpPlus\\WpOopBase\\Custom\\PostType\\AbstractCustomPostType' => $baseDir . '/src/Custom/PostType/AbstractCustomPostType.php',
    'WpPlus\\WpOopBase\\Custom\\Taxonomy\\AbstractCustomTaxonomy' => $baseDir . '/src/Custom/Taxonomy/AbstractCustomTaxonomy.php',
    'WpPlus\\WpOopBase\\Helper\\DateTime' => $baseDir . '/src/Helper/DateTime.php',
    'WpPlus\\WpOopBase\\Helper\\Post' => $baseDir . '/src/Helper/Post.php',
    'WpPlus\\WpOopBase\\Hook\\AbstractActivationHook' => $baseDir . '/src/Hook/AbstractActivationHook.php',
    'WpPlus\\WpOopBase\\Hook\\AbstractHook' => $baseDir . '/src/Hook/AbstractHook.php',
    'WpPlus\\WpOopBase\\Hook\\AbstractMultiHook' => $baseDir . '/src/Hook/AbstractMultiHook.php',
    'WpPlus\\WpOopBase\\Plugin\\AbstractExtensiblePlugin' => $baseDir . '/src/Plugin/AbstractExtensiblePlugin.php',
    'WpPlus\\WpOopBase\\Plugin\\AbstractPlugin' => $baseDir . '/src/Plugin/AbstractPlugin.php',
    'WpPlus\\WpOopBase\\Plugin\\PluginsContainerTrait' => $baseDir . '/src/Plugin/PluginsContainerTrait.php',
    'WpPlus\\WpOopBase\\Registrable\\AbstractRegistrable' => $baseDir . '/src/Registrable/AbstractRegistrable.php',
    'WpPlus\\WpOopBase\\Registrable\\RegistrableInterface' => $baseDir . '/src/Registrable/RegistrableInterface.php',
    'WpPlus\\WpOopBase\\Runnable\\AbstractRunnable' => $baseDir . '/src/Runnable/AbstractRunnable.php',
    'WpPlus\\WpOopBase\\Runnable\\RunnableInterface' => $baseDir . '/src/Runnable/RunnableInterface.php',
    'WpPlus\\WpOopBase\\Shortcode\\AbstractShortcode' => $baseDir . '/src/Shortcode/AbstractShortcode.php',
    'WpPlus\\WpOopBase\\Support\\AllowStaticMethodCallsTrait' => $baseDir . '/src/Support/AllowStaticMethodCallsTrait.php',
    'WpPlus\\WpOopBase\\Support\\WpDbTrait' => $baseDir . '/src/Support/WpDbTrait.php',
);
