<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'WpPlus\\WpOopBase\\Custom\\PostType\\AbstractCustomPostType' => $baseDir . '/src/Custom/PostType/AbstractCustomPostType.php',
    'WpPlus\\WpOopBase\\Custom\\Taxonomy\\AbstractCustomTaxonomy' => $baseDir . '/src/Custom/Taxonomy/AbstractCustomTaxonomy.php',
    'WpPlus\\WpOopBase\\Hook\\AbstractActivationHook' => $baseDir . '/src/Hook/AbstractActivationHook.php',
    'WpPlus\\WpOopBase\\Hook\\AbstractHook' => $baseDir . '/src/Hook/AbstractHook.php',
    'WpPlus\\WpOopBase\\Hook\\HooksContainerTrait' => $baseDir . '/src/Hook/HooksContainerTrait.php',
    'WpPlus\\WpOopBase\\Plugin\\AbstractExtensiblePlugin' => $baseDir . '/src/Plugin/AbstractExtensiblePlugin.php',
    'WpPlus\\WpOopBase\\Plugin\\AbstractPlugin' => $baseDir . '/src/Plugin/AbstractPlugin.php',
    'WpPlus\\WpOopBase\\Plugin\\PluginsContainerTrait' => $baseDir . '/src/Plugin/PluginsContainerTrait.php',
);
