<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6551e1500547f2625b1607f45e096353
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WpPlus\\WpOopBase\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WpPlus\\WpOopBase\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6551e1500547f2625b1607f45e096353::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6551e1500547f2625b1607f45e096353::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit6551e1500547f2625b1607f45e096353::$classMap;

        }, null, ClassLoader::class);
    }
}
