<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'WpPlus\\WpOopBase\\Common\\AllowStaticMethodCallsTrait' => $baseDir . '/src/Common/AllowStaticMethodCallsTrait.php',
    'WpPlus\\WpOopBase\\Common\\Registrable\\AbstractRegistrable' => $baseDir . '/src/Common/Registrable/AbstractRegistrable.php',
    'WpPlus\\WpOopBase\\Common\\Registrable\\RegistrableInterface' => $baseDir . '/src/Common/Registrable/RegistrableInterface.php',
    'WpPlus\\WpOopBase\\Common\\Runnable\\AbstractRunnable' => $baseDir . '/src/Common/Runnable/AbstractRunnable.php',
    'WpPlus\\WpOopBase\\Common\\Runnable\\RunnableInterface' => $baseDir . '/src/Common/Runnable/RunnableInterface.php',
    'WpPlus\\WpOopBase\\Custom\\PostType\\AbstractCustomPostType' => $baseDir . '/src/Custom/PostType/AbstractCustomPostType.php',
    'WpPlus\\WpOopBase\\Custom\\Taxonomy\\AbstractCustomTaxonomy' => $baseDir . '/src/Custom/Taxonomy/AbstractCustomTaxonomy.php',
    'WpPlus\\WpOopBase\\Hook\\AbstractActivationHook' => $baseDir . '/src/Hook/AbstractActivationHook.php',
    'WpPlus\\WpOopBase\\Hook\\AbstractHook' => $baseDir . '/src/Hook/AbstractHook.php',
    'WpPlus\\WpOopBase\\Hook\\AbstractMultiHook' => $baseDir . '/src/Hook/AbstractMultiHook.php',
    'WpPlus\\WpOopBase\\Plugin\\AbstractExtensiblePlugin' => $baseDir . '/src/Plugin/AbstractExtensiblePlugin.php',
    'WpPlus\\WpOopBase\\Plugin\\AbstractPlugin' => $baseDir . '/src/Plugin/AbstractPlugin.php',
    'WpPlus\\WpOopBase\\Plugin\\PluginsContainerTrait' => $baseDir . '/src/Plugin/PluginsContainerTrait.php',
);
